# Generated by Django 4.2.6 on 2023-10-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('type', models.IntegerField(choices=[(0, 'researching'), (1, 'on-a-bike'), (2, 'in-new-places'), (3, 'lost-in-space'), (4, 'thinking'), (5, 'applying'), (6, 'currently')], default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('caption', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('created_on', models.DateField()),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('fulltext', models.TextField(blank=True)),
                ('post_type', models.IntegerField(choices=[(0, 'researching'), (1, 'on-a-bike'), (2, 'in-new-places'), (3, 'lost-in-space'), (4, 'thinking'), (5, 'applying'), (6, 'currently')], default=0)),
                ('cover_photo', models.ImageField(upload_to='cover_photos/')),
                ('created_on', models.DateField()),
                ('html_file', models.CharField(default='building_blocks/post-detail.html', max_length=200)),
                ('additional_html', models.TextField(blank=True)),
                ('location', models.ManyToManyField(to='core.location')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
