# Generated by Django 4.1.5 on 2023-01-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astro_photo',
            name='photo',
            field=models.ImageField(upload_to='space/'),
        ),
    ]
