# Generated by Django 3.2.16 on 2023-01-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230127_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Locations',
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.ManyToManyField(to='core.Location'),
        ),
    ]
