# Generated by Django 4.1.5 on 2024-07-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='link',
        ),
        migrations.AddField(
            model_name='album',
            name='link',
            field=models.CharField(blank=True, default='https://www.dahlia.is/here', max_length=200, null=True),
        ),
    ]
