# Generated by Django 3.2.16 on 2023-01-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230127_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('caption', models.TextField()),
                ('type', models.IntegerField(choices=[(0, 'project'), (1, 'outside'), (2, 'travel'), (3, 'astro'), (4, 'writing'), (5, 'job')], default=0)),
                ('image', models.ImageField(upload_to='<django.db.models.fields.IntegerField>/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('group', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_photo',
            field=models.ImageField(upload_to='cover_photos/'),
        ),
    ]
