# Generated by Django 4.1.5 on 2024-07-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_photo_link_album_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='show_on_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
