# Generated by Django 4.2.6 on 2023-10-10 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_album_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='additional_html',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='html_file',
            new_name='html',
        ),
        migrations.RemoveField(
            model_name='post',
            name='fulltext',
        ),
    ]
