# Generated by Django 3.2.16 on 2023-01-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230127_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='created_on',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateField(),
        ),
    ]
