# Generated by Django 4.2.6 on 2023-10-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_additional_html_post_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.FilePathField(path='content/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='html',
            field=models.FilePathField(default='templates/building_blocks/post-detail.html', max_length=200, path='templates/'),
        ),
    ]
