# Generated by Django 4.2.6 on 2023-10-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_post_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.FilePathField(path='content/', recursive=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='html',
            field=models.FilePathField(default='templates/building_blocks/post-detail.html', max_length=200, path='core/templates/', recursive=True),
        ),
    ]
