# Generated by Django 3.2.16 on 2023-01-27 21:52

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('core', '0008_alter_photo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('type', models.IntegerField(choices=[(0, 'project'), (1, 'outside'), (2, 'travel'), (3, 'astro'), (4, 'writing'), (5, 'job')], default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('caption', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('created_on', models.DateField()),
                ('album', models.ManyToManyField(to='core.Album')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('summary', models.TextField()),
                ('fulltext', models.TextField()),
                ('type', models.IntegerField(choices=[(0, 'project'), (1, 'outside'), (2, 'travel'), (3, 'astro'), (4, 'writing'), (5, 'job')], default=0)),
                ('cover_photo', models.ImageField(upload_to='cover_photos/')),
                ('created_on', models.DateField()),
                ('use_template', models.BooleanField()),
                ('location', models.ManyToManyField(to='core.Location')),
                ('photo_group', models.ManyToManyField(blank=True, to='core.Album')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
