# Generated by Django 4.2.6 on 2023-10-12 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_album_sync_location_photo_filename_alter_photo_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='type',
        ),
    ]
