# Generated by Django 3.2.16 on 2023-02-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20230127_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='type',
            field=models.IntegerField(choices=[(0, 'project'), (1, 'outside'), (2, 'travel'), (3, 'astro'), (4, 'writing'), (5, 'job'), (6, 'current project')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.IntegerField(choices=[(0, 'project'), (1, 'outside'), (2, 'travel'), (3, 'astro'), (4, 'writing'), (5, 'job'), (6, 'current project')], default=0),
        ),
    ]
