# Generated by Django 3.2.16 on 2023-02-02 22:03

from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('core', '0011_auto_20230201_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='AstroPhoto',
            fields=[
                ('photo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.photo')),
                ('instruments', models.TextField()),
                ('catalogue_name', models.TextField(blank=True)),
                ('link', models.TextField(blank=True)),
            ],
            bases=('core.photo',),
        ),
        migrations.AddField(
            model_name='photo',
            name='location',
            field=models.ManyToManyField(to='core.Location'),
        ),
        migrations.AddField(
            model_name='post',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('cover_photo', '550x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='caption',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='fulltext',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
