# Generated by Django 4.2.6 on 2023-10-12 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_photo_album_photo_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='AstroPhoto',
            fields=[
                ('photo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.photo')),
                ('instruments', models.TextField(blank=True)),
                ('catalog_name', models.TextField(blank=True)),
                ('link', models.TextField(blank=True)),
            ],
            bases=('core.photo',),
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['album', '-created_on']},
        ),
    ]
