# Generated by Django 3.2.16 on 2023-02-02 22:06

from django.db import migrations, models
import image_cropping.fields
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('core', '0012_auto_20230202_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cropping',
        ),
        migrations.CreateModel(
            name='Postcrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('fulltext', models.TextField(blank=True)),
                ('type', models.IntegerField(choices=[(0, 'project'), (1, 'outside'), (2, 'travel'), (3, 'astro'), (4, 'writing'), (5, 'job'), (6, 'current project')], default=0)),
                ('cover_photo', models.ImageField(upload_to='cover_photos/')),
                ('cropping', image_cropping.fields.ImageRatioField('cover_photo', '550x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('created_on', models.DateField()),
                ('use_template', models.BooleanField()),
                ('location', models.ManyToManyField(to='core.Location')),
                ('photo_group', models.ManyToManyField(blank=True, to='core.Album')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
