# Generated by Django 4.1.5 on 2023-02-07 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20230202_2206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Postcrop',
        ),
    ]
