# Generated by Django 4.2.6 on 2023-10-12 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_astrophoto_alter_photo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.photo'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='location',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.location'),
        ),
    ]
