# Generated by Django 4.2.6 on 2023-10-12 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_post_cover_photo_remove_post_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cover_photo',
        ),
        migrations.AddField(
            model_name='post',
            name='cover_photos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.photo'),
            preserve_default=False,
        ),
    ]
