# Generated by Django 4.1.5 on 2023-02-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_delete_postcrop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='astrophoto',
            old_name='catalogue_name',
            new_name='catalog_name',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='type',
            new_name='post_type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo_group',
        ),
        migrations.RemoveField(
            model_name='post',
            name='use_template',
        ),
        migrations.AddField(
            model_name='post',
            name='html_file',
            field=models.CharField(default='building_blocks/base.html', max_length=200),
        ),
        migrations.AlterField(
            model_name='astrophoto',
            name='instruments',
            field=models.TextField(blank=True),
        ),
    ]
