# Generated by Django 4.2.6 on 2023-10-12 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_post_cover_photo_post_cover_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cover_photos',
        ),
    ]
