# Generated by Django 4.1.5 on 2023-02-07 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_catalogue_name_astrophoto_catalog_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='location',
        ),
        migrations.AddField(
            model_name='photo',
            name='location',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='core.location'),
            preserve_default=False,
        ),
    ]
