# Generated by Django 4.2.6 on 2023-10-12 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_post_cover_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_photo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.photo'),
            preserve_default=False,
        ),
    ]
