# Generated by Django 4.2.6 on 2023-10-20 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cover_photo',
        ),
        migrations.AddField(
            model_name='photo',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.post'),
        ),
        migrations.AddField(
            model_name='photo',
            name='show_on_homepage',
            field=models.BooleanField(default=True),
        ),
    ]
