# Generated by Django 4.2.6 on 2023-10-20 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_post_cover_photo_photo_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='post',
            new_name='post_obj',
        ),
        migrations.AddField(
            model_name='post',
            name='cover_photo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.photo'),
            preserve_default=False,
        ),
    ]
