# Generated by Django 4.2.6 on 2023-10-20 11:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_post_photo_post_obj_post_cover_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='astrophoto',
            old_name='link',
            new_name='info_link',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='post_obj',
        ),
        migrations.AddField(
            model_name='astrophoto',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='link',
            field=models.CharField(blank=True, default='https://www.dahlia.is/here', max_length=200, null=True),
        ),
    ]
