# Generated by Django 4.2.6 on 2023-10-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_link_astrophoto_info_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='astrophoto',
            name='instruments',
        ),
        migrations.AddField(
            model_name='astrophoto',
            name='instruments',
            field=models.ManyToManyField(blank=True, null=True, to='core.instrument'),
        ),
    ]
