# Generated by Django 4.2.6 on 2023-10-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_instrument_remove_astrophoto_instruments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astrophoto',
            name='instruments',
            field=models.ManyToManyField(blank=True, to='core.instrument'),
        ),
    ]
