# Generated by Django 4.2.6 on 2023-10-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_astrophoto_instruments'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='name_short',
            field=models.CharField(blank=True, default=models.CharField(max_length=200), max_length=200, null=True),
        ),
    ]
