# Generated by Django 4.2.6 on 2023-10-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_instrument_name_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='name_short',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
