# Generated by Django 4.2.6 on 2023-10-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_instrument_name_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrophoto',
            name='instrument_caption',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
