# Generated by Django 4.2.6 on 2023-10-22 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_astrophoto_instrument_caption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='astrophoto',
            old_name='instrument_caption',
            new_name='inst_caption',
        ),
    ]
