# Generated by Django 4.2.6 on 2023-10-22 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_rename_instrument_caption_astrophoto_inst_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='astrophoto',
            name='uid',
        ),
    ]
