# Generated by Django 4.2.6 on 2023-10-22 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_astrophoto_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='summary',
        ),
    ]
