# Generated by Django 4.2.6 on 2023-10-23 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_post_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.photo'),
        ),
    ]
