# Generated by Django 4.2.6 on 2023-10-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_post_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
