# Generated by Django 4.2.6 on 2023-11-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_post_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='show_on_homepage',
            field=models.BooleanField(default=True),
        ),
    ]
